### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by DaveSprague** [RuleWorld/BNG_vscode_extension#5]
I'm running on Windows 10 with the VSCode extension for bionetgen extension and with Anaconda installed.
I'm doing the first example in the Introductory powerpoint presentation at 2021 Cell Modeling Workshop which is linked at the Getting Started section of the https://bionetgen.org/

When I run it using the "flagman" icon or just using the command line command I get this error:
FileNotFoundError: [WinError 2] The system cannot find the file specified

I tried getting the absolute and the relative paths to the input file from VS Code and pasting those into the command line as well but that didn't fix the problem.  It appears that bionetgen can not find the input file for some reason.

Any suggestions would be appreciated.

![image](https://user-images.githubusercontent.com/1448202/151458310-822e19f3-49fc-4714-a7ab-10ef5abc3710.png)

**Comment by ASinanSaglam** [comment]
Thank you for the detailed issue! 

Just wanted to let you know that I'm looking into this.

**Comment by DaveSprague** [comment]
Thank you

**Comment by ASinanSaglam** [comment]
Can you run ```bionetgen info``` in your terminal manually and send me the result?

**Comment by DaveSprague** [comment]
This looks promising, maybe I have a missing library?
Here's the output from* bionetget info*:

(base)
C:\Users\David\OneDrive\Documents\Programming\python\BioNetGen>bionetgen
info
Traceback (most recent call last):
  File "C:\Users\David\anaconda3\lib\runpy.py", line 197, in
_run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\David\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\David\anaconda3\Scripts\bionetgen.exe\__main__.py", line
7, in <module>
  File "C:\Users\David\anaconda3\lib\site-packages\bionetgen\main.py", line
666, in main
    app.run()
  File
"C:\Users\David\anaconda3\lib\site-packages\cement\core\foundation.py",
line 916, in run
    return_val = self.controller._dispatch()
  File
"C:\Users\David\anaconda3\lib\site-packages\cement\ext\ext_argparse.py",
line 810, in _dispatch
    return func()
  File "C:\Users\David\anaconda3\lib\site-packages\bionetgen\main.py", line
338, in info
    printInfo(self.app.config, args)
  File "C:\Users\David\anaconda3\lib\site-packages\bionetgen\core\main.py",
line 99, in printInfo
    info.gatherInfo()
  File
"C:\Users\David\anaconda3\lib\site-packages\bionetgen\tools\info.py", line
26, in gatherInfo
    import roadrunner
ModuleNotFoundError: No module named 'roadrunner'


(base) C:\Users\David\OneDrive\Documents\Programming\python\BioNetGen>

**Comment by ASinanSaglam** [comment]
Hmm, at least it's a start, I'm unsure if the original problem was related. `pip install bionetgen` should have installed libroadrunner as well. 

Can you try running `pip install libroadrunner` and try again?

**Comment by DaveSprague** [comment]
I installed libroadrunner and received this output:

(base) C:\Users\David\OneDrive\Documents\Programming\python\BioNetGen>pip
install libroadrunner Collecting libroadrunner
  Downloading libroadrunner-2.2.0-cp39-cp39-win_amd64.whl (26.3 MB)
     |████████████████████████████████| 26.3 MB 6.8 MB/s
Collecting numpy>=1.22.0
  Downloading numpy-1.22.1-cp39-cp39-win_amd64.whl (14.7 MB)
     |████████████████████████████████| 14.7 MB 6.8 MB/s
Installing collected packages: numpy, libroadrunner
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
ERROR: pip's dependency resolver does not currently take into account all
the packages that are installed. This behaviour is the source of the
following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.22.1 which is
incompatible.
Successfully installed libroadrunner-2.2.0 numpy-1.22.1

So I tried uninstalling numpy and reinstalling it with "pip install
numpy==1.21" but then I received this:

(base) C:\Users\David\OneDrive\Documents\Programming\python\BioNetGen>pip
install numpy==1.21
Collecting numpy==1.21
  Downloading numpy-1.21.0-cp39-cp39-win_amd64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 6.4 MB/s
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all
the packages that are installed. This behaviour is the source of the
following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.21.0 which is
incompatible.
libroadrunner 2.2.0 requires numpy>=1.22.0; python_version > "3.7", but you
have numpy 1.21.0 which is incompatible.
Successfully installed numpy-1.21.0

Should I keep going, trying to get a set of compatible interdependent
libraries?

If I run bionetgen info now, I get:

(base)
C:\Users\David\OneDrive\Documents\Programming\python\BioNetGen>bionetgen
info
RuntimeError: module compiled against API version 0xf but this version of
numpy is 0xe
Traceback (most recent call last):
  File "C:\Users\David\anaconda3\lib\runpy.py", line 197, in
_run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\David\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\David\anaconda3\Scripts\bionetgen.exe\__main__.py", line
7, in <module>
  File "C:\Users\David\anaconda3\lib\site-packages\bionetgen\main.py", line
666, in main
    app.run()
  File
"C:\Users\David\anaconda3\lib\site-packages\cement\core\foundation.py",
line 916, in run
    return_val = self.controller._dispatch()
  File
"C:\Users\David\anaconda3\lib\site-packages\cement\ext\ext_argparse.py",
line 810, in _dispatch
    return func()
  File "C:\Users\David\anaconda3\lib\site-packages\bionetgen\main.py", line
338, in info
    printInfo(self.app.config, args)
  File "C:\Users\David\anaconda3\lib\site-packages\bionetgen\core\main.py",
line 99, in printInfo
    info.gatherInfo()
  File
"C:\Users\David\anaconda3\lib\site-packages\bionetgen\tools\info.py", line
26, in gatherInfo
    import roadrunner
  File "C:\Users\David\anaconda3\lib\site-packages\roadrunner\__init__.py",
line 10, in <module>
    from .roadrunner import *
  File
"C:\Users\David\anaconda3\lib\site-packages\roadrunner\roadrunner.py", line
15, in <module>
    from . import _roadrunner
ImportError: numpy.core.multiarray failed to import

**Comment by DaveSprague** [comment]
I"m thinking I'll need to create a new conda environment with no libraries
loaded, and then install bionetgen and let it install the versions of
libraries it needs?
I don't recall seeing errors when In installed bionetgen but maybe I just
didn't catch them.

Dave

**Comment by ASinanSaglam** [comment]
That's a really good call. I was aware of a pandas version mismatch and some numpy version issues (that's why I had specific versions defined in Pybionetgen [dependencies](https://github.com/RuleWorld/PyBioNetGen/blob/main/requirements.txt) but I haven't had any issues with my testing recently. 

Can you also post the anaconda version you used whenever it's convenient for you? I'd like to replicate the issue and fix it on this end if I can.

**Comment by DaveSprague** [comment]
"conda -V" gives me:
conda 4.11.0

Anaconda Navigator version is 1.9.1

Are those what you need?

**Comment by ASinanSaglam** [comment]
That should be enough, thank you!

**Comment by DaveSprague** [comment]
I did a fresh install of anaconda on a different windows 11 computer.  I
then created a new Conda environment with python 3.9.7 and then did a pip
install bionetgen it installed a bunch of packages but when I run it in VS
Code with the bionetgen extension, it still has the same issue of missing
the roadrunner module.

Here's the output from when I did pip install bionetgen:

(bionetgen) C:\Users\David>pip install bionetgen
Collecting bionetgen
  Downloading bionetgen-0.6.2-py3-none-any.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 1.6 MB/s
Collecting nbopen
  Downloading nbopen-0.6-py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 5.8 MB/s
Collecting numpy
  Downloading numpy-1.22.1-cp39-cp39-win_amd64.whl (14.7 MB)
     |████████████████████████████████| 14.7 MB 6.8 MB/s
Collecting colorlog
  Downloading colorlog-6.6.0-py2.py3-none-any.whl (11 kB)
Collecting xmltodict
  Downloading xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting seaborn
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting cement
  Downloading cement-3.0.6-py3-none-any.whl (291 kB)
     |████████████████████████████████| 291 kB 6.4 MB/s
Collecting pyyaml
  Downloading PyYAML-6.0-cp39-cp39-win_amd64.whl (151 kB)
     |████████████████████████████████| 151 kB ...
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting notebook
  Downloading notebook-6.4.8-py3-none-any.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 6.8 MB/s
Collecting nbformat
  Using cached nbformat-5.1.3-py3-none-any.whl (178 kB)
Collecting jsonschema!=2.5.0,>=2.4
  Downloading jsonschema-4.4.0-py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB ...
Collecting traitlets>=4.1
  Using cached traitlets-5.1.1-py3-none-any.whl (102 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting jupyter-core
  Using cached jupyter_core-4.9.1-py3-none-any.whl (86 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp39-cp39-win_amd64.whl (61 kB)
     |████████████████████████████████| 61 kB 77 kB/s
Collecting attrs>=17.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting pywin32>=1.0
  Using cached pywin32-303-cp39-cp39-win_amd64.whl (9.3 MB)
Collecting prometheus-client
  Downloading prometheus_client-0.13.1-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 3.8 MB/s
Collecting jinja2
  Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting ipykernel
  Downloading ipykernel-6.7.0-py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 6.4 MB/s
Collecting Send2Trash>=1.8.0
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting nest-asyncio>=1.5
  Using cached nest_asyncio-1.5.4-py3-none-any.whl (5.1 kB)
Collecting pyzmq>=17
  Using cached pyzmq-22.3.0-cp39-cp39-win_amd64.whl (1.0 MB)
Collecting argon2-cffi
  Using cached argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting jupyter-client>=5.3.4
  Downloading jupyter_client-7.1.2-py3-none-any.whl (130 kB)
     |████████████████████████████████| 130 kB ...
Collecting tornado>=6.1
  Using cached tornado-6.1-cp39-cp39-win_amd64.whl (422 kB)
Collecting nbconvert
  Downloading nbconvert-6.4.1-py3-none-any.whl (557 kB)
     |████████████████████████████████| 557 kB 6.4 MB/s
Collecting terminado>=0.8.3
  Downloading terminado-0.13.1-py3-none-any.whl (14 kB)
Collecting entrypoints
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pywinpty>=1.1.0
  Downloading pywinpty-2.0.1-cp39-none-win_amd64.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 6.4 MB/s
Collecting argon2-cffi-bindings
  Using cached argon2_cffi_bindings-21.2.0-cp36-abi3-win_amd64.whl (30 kB)
Collecting cffi>=1.0.1
  Using cached cffi-1.15.0-cp39-cp39-win_amd64.whl (180 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting ipython>=7.23.1
  Downloading ipython-8.0.1-py3-none-any.whl (747 kB)
     |████████████████████████████████| 747 kB ...
Collecting debugpy<2.0,>=1.0.0
  Using cached debugpy-1.5.1-cp39-cp39-win_amd64.whl (4.4 MB)
Collecting matplotlib-inline<0.2.0,>=0.1.0
  Using cached matplotlib_inline-0.1.3-py3-none-any.whl (8.2 kB)
Collecting stack-data
  Downloading stack_data-0.1.4-py3-none-any.whl (20 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting pygments
  Downloading Pygments-2.11.2-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 6.8 MB/s
Collecting jedi>=0.16
  Using cached jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.26-py3-none-any.whl (375 kB)
     |████████████████████████████████| 375 kB 3.3 MB/s
Collecting black
  Downloading black-21.12b0-py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 6.8 MB/s
Requirement already satisfied: setuptools>=18.5 in
c:\users\david\anaconda3\envs\bionetgen\lib\site-packages (from
ipython>=7.23.1->ipykernel->notebook->nbopen->bionetgen) (58.0.4)
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting click>=7.1.2
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting typing-extensions>=3.10.0.0
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting platformdirs>=2
  Downloading platformdirs-2.4.1-py3-none-any.whl (14 kB)
Collecting tomli<2.0.0,>=0.2.6
  Downloading tomli-1.2.3-py3-none-any.whl (12 kB)
Collecting pathspec<1,>=0.9.0
  Downloading pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.0.1-cp39-cp39-win_amd64.whl (14 kB)
Collecting pandocfilters>=1.4.1
  Using cached pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting jupyterlab-pygments
  Using cached jupyterlab_pygments-0.1.2-py2.py3-none-any.whl (4.6 kB)
Collecting testpath
  Using cached testpath-0.5.0-py3-none-any.whl (84 kB)
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting nbclient<0.6.0,>=0.5.0
  Downloading nbclient-0.5.10-py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 4.8 MB/s
Collecting bleach
  Using cached bleach-4.1.0-py2.py3-none-any.whl (157 kB)
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.7-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 3.7 MB/s
Collecting pandas>=0.23
  Downloading pandas-1.4.0-cp39-cp39-win_amd64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 6.4 MB/s
Collecting matplotlib>=2.2
  Using cached matplotlib-3.5.1-cp39-cp39-win_amd64.whl (7.2 MB)
Collecting scipy>=1.0
  Using cached scipy-1.7.3-cp39-cp39-win_amd64.whl (34.3 MB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.29.0-py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB ...
Collecting pillow>=6.2.0
  Downloading Pillow-9.0.0-cp39-cp39-win_amd64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 6.4 MB/s
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.2-cp39-cp39-win_amd64.whl (52 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pytz>=2020.1
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting asttokens
  Downloading asttokens-2.0.5-py2.py3-none-any.whl (20 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing
  Downloading executing-0.8.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: traitlets, six, pywin32, pyrsistent,
colorama, attrs, wcwidth, typing-extensions, tornado, tomli, pyzmq,
python-dateutil, pyparsing, pycparser, pure-eval, platformdirs, pathspec,
parso, nest-asyncio, mypy-extensions, jupyter-core, jsonschema,
ipython-genutils, executing, entrypoints, click, asttokens, webencodings,
stack-data, pygments, prompt-toolkit, pickleshare, packaging, nbformat,
matplotlib-inline, MarkupSafe, jupyter-client, jedi, decorator, cffi,
black, backcall, testpath, pywinpty, pandocfilters, nbclient, mistune,
jupyterlab-pygments, jinja2, ipython, defusedxml, debugpy, bleach,
argon2-cffi-bindings, terminado, Send2Trash, pytz, prometheus-client,
pillow, numpy, nbconvert, kiwisolver, ipykernel, fonttools, cycler,
argon2-cffi, scipy, pandas, notebook, matplotlib, xmltodict, seaborn,
pyyaml, nbopen, colorlog, cement, bionetgen
Successfully installed MarkupSafe-2.0.1 Send2Trash-1.8.0 argon2-cffi-21.3.0
argon2-cffi-bindings-21.2.0 asttokens-2.0.5 attrs-21.4.0 backcall-0.2.0
bionetgen-0.6.2 black-21.12b0 bleach-4.1.0 cement-3.0.6 cffi-1.15.0
click-8.0.3 colorama-0.4.4 colorlog-6.6.0 cycler-0.11.0 debugpy-1.5.1
decorator-5.1.1 defusedxml-0.7.1 entrypoints-0.3 executing-0.8.2
fonttools-4.29.0 ipykernel-6.7.0 ipython-8.0.1 ipython-genutils-0.2.0
jedi-0.18.1 jinja2-3.0.3 jsonschema-4.4.0 jupyter-client-7.1.2
jupyter-core-4.9.1 jupyterlab-pygments-0.1.2 kiwisolver-1.3.2
matplotlib-3.5.1 matplotlib-inline-0.1.3 mistune-0.8.4
mypy-extensions-0.4.3 nbclient-0.5.10 nbconvert-6.4.1 nbformat-5.1.3
nbopen-0.6 nest-asyncio-1.5.4 notebook-6.4.8 numpy-1.22.1 packaging-21.3
pandas-1.4.0 pandocfilters-1.5.0 parso-0.8.3 pathspec-0.9.0
pickleshare-0.7.5 pillow-9.0.0 platformdirs-2.4.1 prometheus-client-0.13.1
prompt-toolkit-3.0.26 pure-eval-0.2.2 pycparser-2.21 pygments-2.11.2
pyparsing-3.0.7 pyrsistent-0.18.1 python-dateutil-2.8.2 pytz-2021.3
pywin32-303 pywinpty-2.0.1 pyyaml-6.0 pyzmq-22.3.0 scipy-1.7.3
seaborn-0.11.2 six-1.16.0 stack-data-0.1.4 terminado-0.13.1 testpath-0.5.0
tomli-1.2.3 tornado-6.1 traitlets-5.1.1 typing-extensions-4.0.1
wcwidth-0.2.5 webencodings-0.5.1 xmltodict-0.12.0


I don't see libroadrunner being installed here.

If I now do pip install libroadrunner, it appears to complete correctly:

(bionetgen) C:\Users\David>pip install libroadrunner
Collecting libroadrunner
  Downloading libroadrunner-2.2.0-cp39-cp39-win_amd64.whl (26.3 MB)
     |████████████████████████████████| 26.3 MB 6.4 MB/s
Requirement already satisfied: numpy>=1.22.0 in
c:\users\david\anaconda3\envs\bionetgen\lib\site-packages (from
libroadrunner) (1.22.1)
Installing collected packages: libroadrunner
Successfully installed libroadrunner-2.2.0

But when I run "bionetgen info", I get this:

(bionetgen) C:\Users\David>bionetgen info
Traceback (most recent call last):
  File "C:\Users\David\anaconda3\envs\bionetgen\lib\runpy.py", line 197, in
_run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\David\anaconda3\envs\bionetgen\lib\runpy.py", line 87, in
_run_code
    exec(code, run_globals)
  File
"C:\Users\David\anaconda3\envs\bionetgen\Scripts\bionetgen.exe\__main__.py",
line 7, in <module>
  File
"C:\Users\David\anaconda3\envs\bionetgen\lib\site-packages\bionetgen\main.py",
line 666, in main
    app.run()
  File
"C:\Users\David\anaconda3\envs\bionetgen\lib\site-packages\cement\core\foundation.py",
line 916, in run
    return_val = self.controller._dispatch()
  File
"C:\Users\David\anaconda3\envs\bionetgen\lib\site-packages\cement\ext\ext_argparse.py",
line 810, in _dispatch
    return func()
  File
"C:\Users\David\anaconda3\envs\bionetgen\lib\site-packages\bionetgen\main.py",
line 338, in info
    printInfo(self.app.config, args)
  File
"C:\Users\David\anaconda3\envs\bionetgen\lib\site-packages\bionetgen\core\main.py",
line 99, in printInfo
    info.gatherInfo()
  File
"C:\Users\David\anaconda3\envs\bionetgen\lib\site-packages\bionetgen\tools\info.py",
line 50, in gatherInfo
    result = subprocess.run(["perl", "-v"], stdout=subprocess.PIPE)
  File "C:\Users\David\anaconda3\envs\bionetgen\lib\subprocess.py", line
505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\David\anaconda3\envs\bionetgen\lib\subprocess.py", line
951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\David\anaconda3\envs\bionetgen\lib\subprocess.py", line
1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified



Here's the list of packages installed:

(BioNetGen) C:\Users\David\OneDrive\Documents\Programming\python\Colorspace
Project\ColorSpace>pip list
Package              Version
-------------------- ---------
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
backcall             0.2.0
bionetgen            0.6.2
black                21.12b0
bleach               4.1.0
cement               3.0.6
certifi              2021.10.8
cffi                 1.15.0
click                8.0.3
colorama             0.4.4
colorlog             6.6.0
cycler               0.11.0
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.3
executing            0.8.2
fonttools            4.29.0
ipykernel            6.7.0
ipython              8.0.1
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.0.3
jsonschema           4.4.0
jupyter-client       7.1.2
jupyter-core         4.9.1
jupyterlab-pygments  0.1.2
kiwisolver           1.3.2
libroadrunner        2.2.0
MarkupSafe           2.0.1
matplotlib           3.5.1
matplotlib-inline    0.1.3
mistune              0.8.4
mypy-extensions      0.4.3
nbclient             0.5.10
nbconvert            6.4.1
nbformat             5.1.3
nbopen               0.6
nest-asyncio         1.5.4
notebook             6.4.8
numpy                1.22.1
packaging            21.3
pandas               1.4.0
pandocfilters        1.5.0
parso                0.8.3
pathspec             0.9.0
pickleshare          0.7.5
Pillow               9.0.0
pip                  21.2.4
platformdirs         2.4.1
prometheus-client    0.13.1
prompt-toolkit       3.0.26
pure-eval            0.2.2
pycparser            2.21
Pygments             2.11.2
pyparsing            3.0.7
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2021.3
pywin32              303
pywinpty             2.0.1
PyYAML               6.0
pyzmq                22.3.0
scipy                1.7.3
seaborn              0.11.2
Send2Trash           1.8.0
setuptools           58.0.4
six                  1.16.0
stack-data           0.1.4
terminado            0.13.1
testpath             0.5.0
tomli                1.2.3
tornado              6.1
traitlets            5.1.1
typing_extensions    4.0.1
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.37.1
wincertstore         0.2
xmltodict            0.12.0

**Comment by ASinanSaglam** [comment]
Ok, this is much better because it's not longer due to libroadrunner or a missing package. It's having trouble finding the bionetgen install it has downloaded, or potentially windows is not letting the python instance reach into that folder. 

Another option is an issue with perl. Can you check if you have perl installed? (`perl -v` or a similar command in the terminal should show it). If you don't, you'll need it and I suggest using [strawberry perl](https://strawberryperl.com/). 

If that ends up being the issue, I'll try to address it on Pybionetgen end so that the user doesn't need to manually do this in the future.

**Comment by DaveSprague** [comment]
I thought I had installed Activate State Perl but I had not.  I installed strawberry perl and now it's working.  Sorry about that.

**Comment by ASinanSaglam** [comment]
No need to apologize at all, I appreciate posting the issue. I'll figure out a better way to install perl from Pybionetgen end to avoid this in the future so it was helpful. 

I'm glad it's resolved, let me know if you encounter other issues.

**Comment by DaveSprague** [comment]
Thanks, will do.
